// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SitoDeiSiti.DAL.Models;

public partial class SitoDeiSitiInsitoContext : DbContext
{
    public SitoDeiSitiInsitoContext(DbContextOptions<SitoDeiSitiInsitoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Abbonamento> Abbonamento { get; set; }

    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Cinture> Cinture { get; set; }

    public virtual DbSet<Documento> Documento { get; set; }

    public virtual DbSet<Evento> Evento { get; set; }

    public virtual DbSet<Gare> Gare { get; set; }

    public virtual DbSet<Grafiche> Grafiche { get; set; }

    public virtual DbSet<IscrizioneEvento> IscrizioneEvento { get; set; }

    public virtual DbSet<Notifica> Notifica { get; set; }

    public virtual DbSet<Organizzazioni> Organizzazioni { get; set; }

    public virtual DbSet<Pagine> Pagine { get; set; }

    public virtual DbSet<Redirezioni> Redirezioni { get; set; }

    public virtual DbSet<Template> Template { get; set; }

    public virtual DbSet<TipoAbbonamento> TipoAbbonamento { get; set; }

    public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }

    public virtual DbSet<Utente> Utente { get; set; }

    public virtual DbSet<UtenteAtleta> UtenteAtleta { get; set; }

    public virtual DbSet<UtenteInfo> UtenteInfo { get; set; }

    public virtual DbSet<UtentePrivacy> UtentePrivacy { get; set; }

    public virtual DbSet<Video> Video { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Abbonamento>(entity =>
        {
            entity.HasIndex(e => new { e.Id, e.TipoAbbonamento, e.Utente }, "UC_Abbonamento").IsUnique();

            entity.Property(e => e.DataIscrizione).HasColumnType("date");
            entity.Property(e => e.DataScadenza).HasColumnType("date");
            entity.Property(e => e.IdCheckout).HasMaxLength(255);
            entity.Property(e => e.Importo).HasColumnType("money");
            entity.Property(e => e.UrlPagamento)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.TipoAbbonamentoNavigation).WithMany(p => p.Abbonamento)
                .HasForeignKey(d => d.TipoAbbonamento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AbbonamentoTipoAbbonamento");

            entity.HasOne(d => d.UtenteNavigation).WithMany(p => p.Abbonamento)
                .HasPrincipalKey(p => p.RowGuid)
                .HasForeignKey(d => d.Utente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AbbonamentoUtente");
        });

        modelBuilder.Entity<Categoria>(entity =>
        {
            entity.Property(e => e.Descrizione)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Cinture>(entity =>
        {
            entity.Property(e => e.Tipo).HasMaxLength(255);
        });

        modelBuilder.Entity<Documento>(entity =>
        {
            entity.HasKey(e => e.IdDocumento).HasName("PK_Documento_IdDocumento");

            entity.Property(e => e.IdDocumento).HasDefaultValueSql("(newid())");
            entity.Property(e => e.DataCaricamento).HasColumnType("date");
            entity.Property(e => e.DatiDocumento)
                .IsRequired()
                .HasColumnType("image");
            entity.Property(e => e.NomeDocumento)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.TipoDocumento).WithMany(p => p.Documento)
                .HasForeignKey(d => d.TipoDocumentoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Documento_TipoDocumento");

            entity.HasOne(d => d.Utente).WithMany(p => p.Documento)
                .HasPrincipalKey(p => p.RowGuid)
                .HasForeignKey(d => d.UtenteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Documento_Utente");
        });

        modelBuilder.Entity<Evento>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Categorie).HasMaxLength(255);
            entity.Property(e => e.ChiusuraIscrizioni).HasColumnType("date");
            entity.Property(e => e.Copertina).HasColumnType("image");
            entity.Property(e => e.DataFineEvento).HasColumnType("date");
            entity.Property(e => e.DataInizioEvento).HasColumnType("date");
            entity.Property(e => e.Descrizione).HasMaxLength(1023);
            entity.Property(e => e.ImportoIscrizione).HasColumnType("money");
            entity.Property(e => e.Link).HasMaxLength(1023);
            entity.Property(e => e.LuogoEvento)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NomeEvento)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Gare>(entity =>
        {
            entity.HasIndex(e => new { e.Id, e.Evento }, "UK_Gare").IsUnique();

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ImportoIscrizione).HasColumnType("money");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(1023);

            entity.HasOne(d => d.CategoriaNavigation).WithMany(p => p.Gare)
                .HasForeignKey(d => d.Categoria)
                .HasConstraintName("FK_Gare_Categoria");

            entity.HasOne(d => d.EventoNavigation).WithMany(p => p.Gare)
                .HasForeignKey(d => d.Evento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gare_Evento");
        });

        modelBuilder.Entity<Grafiche>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Immagini");

            entity.Property(e => e.Descrizione).HasMaxLength(255);
            entity.Property(e => e.Titolo).HasMaxLength(255);
            entity.Property(e => e.UrlImmagine).HasMaxLength(1023);

            entity.HasOne(d => d.PaginaNavigation).WithMany(p => p.Grafiche)
                .HasForeignKey(d => d.Pagina)
                .HasConstraintName("FK_Immagini_Pagine");
        });

        modelBuilder.Entity<IscrizioneEvento>(entity =>
        {
            entity.HasKey(e => new { e.IdEvento, e.IdUtente, e.Gara });

            entity.Property(e => e.Note).HasMaxLength(255);

            entity.HasOne(d => d.GaraNavigation).WithMany(p => p.IscrizioneEvento)
                .HasForeignKey(d => d.Gara)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IscrizioneEvento_Gare");

            entity.HasOne(d => d.IdEventoNavigation).WithMany(p => p.IscrizioneEvento)
                .HasForeignKey(d => d.IdEvento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IscrizioneEvento_Evento");

            entity.HasOne(d => d.IdUtenteNavigation).WithMany(p => p.IscrizioneEvento)
                .HasPrincipalKey(p => p.RowGuid)
                .HasForeignKey(d => d.IdUtente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IscrizioneEvento_Utente");
        });

        modelBuilder.Entity<Notifica>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.PaginaNavigation).WithMany(p => p.Notifica)
                .HasForeignKey(d => d.Pagina)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifica_Pagina");
        });

        modelBuilder.Entity<Organizzazioni>(entity =>
        {
            entity.HasKey(e => e.RowGuid);

            entity.Property(e => e.RowGuid).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Descrizione).HasMaxLength(1023);
            entity.Property(e => e.Indirizzo).HasMaxLength(255);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PartitaIva)
                .HasMaxLength(11)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Pagine>(entity =>
        {
            entity.Property(e => e.Pagina)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Redirezioni>(entity =>
        {
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Template>(entity =>
        {
            entity.HasKey(e => e.TemplateName);

            entity.Property(e => e.TemplateName).HasMaxLength(255);
        });

        modelBuilder.Entity<TipoAbbonamento>(entity =>
        {
            entity.Property(e => e.Descrizione).HasMaxLength(50);
        });

        modelBuilder.Entity<TipoDocumento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_TipoDocumento_Id");

            entity.Property(e => e.Descrizione)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Utente>(entity =>
        {
            entity.HasKey(e => e.Email).HasName("PK_Utenti");

            entity.HasIndex(e => e.RowGuid, "UC_Utente").IsUnique();

            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("EMail");
            entity.Property(e => e.CodFiscale).HasMaxLength(16);
            entity.Property(e => e.Cognome).HasMaxLength(50);
            entity.Property(e => e.Nome).HasMaxLength(50);
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.RowGuid).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<UtenteAtleta>(entity =>
        {
            entity.HasKey(e => e.Rowguid);

            entity.Property(e => e.Rowguid).ValueGeneratedNever();

            entity.HasOne(d => d.CinturaNavigation).WithMany(p => p.UtenteAtleta)
                .HasForeignKey(d => d.Cintura)
                .HasConstraintName("FK_UtenteAtleta_Cintura");

            entity.HasOne(d => d.OrganizzazioneNavigation).WithMany(p => p.UtenteAtleta)
                .HasForeignKey(d => d.Organizzazione)
                .HasConstraintName("FK_UtenteAtleta_Organizzazione");

            entity.HasOne(d => d.Row).WithOne(p => p.UtenteAtleta)
                .HasPrincipalKey<Utente>(p => p.RowGuid)
                .HasForeignKey<UtenteAtleta>(d => d.Rowguid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UtenteAtleta_Utente");
        });

        modelBuilder.Entity<UtenteInfo>(entity =>
        {
            entity.HasKey(e => e.RowGuid);

            entity.Property(e => e.RowGuid).ValueGeneratedNever();
            entity.Property(e => e.Citta).HasMaxLength(50);
            entity.Property(e => e.DataNascita).HasColumnType("date");
            entity.Property(e => e.Nazione).HasMaxLength(50);
            entity.Property(e => e.Numero).HasMaxLength(15);
            entity.Property(e => e.Regione).HasMaxLength(50);
            entity.Property(e => e.Via).HasMaxLength(50);

            entity.HasOne(d => d.Row).WithOne(p => p.UtenteInfo)
                .HasPrincipalKey<Utente>(p => p.RowGuid)
                .HasForeignKey<UtenteInfo>(d => d.RowGuid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UtenteInfoUtente");
        });

        modelBuilder.Entity<UtentePrivacy>(entity =>
        {
            entity.HasKey(e => e.RowGuid);

            entity.Property(e => e.RowGuid).ValueGeneratedNever();
        });

        modelBuilder.Entity<Video>(entity =>
        {
            entity.Property(e => e.Descrizione).IsRequired();
            entity.Property(e => e.Provider).HasMaxLength(255);
            entity.Property(e => e.Titolo)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}