// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Grafiche
{
    public int Id { get; set; }

    public string UrlImmagine { get; set; }

    public int? Pagina { get; set; }

    public int? Sezione { get; set; }

    public bool? UrlFromGoogleDrive { get; set; }

    public string Titolo { get; set; }

    public string Descrizione { get; set; }

    public string TestoAggiuntivo { get; set; }

    public bool? IsTestoAggiuntivoMarkdown { get; set; }

    public int? Ordine { get; set; }

    public bool Attiva { get; set; }

    public virtual Pagine PaginaNavigation { get; set; }
}