// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Notifica
{
    public Guid Id { get; set; }

    public int Pagina { get; set; }

    public string Testo { get; set; }

    public bool? Abilitata { get; set; }

    public virtual Pagine PaginaNavigation { get; set; }
}