// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Pagine
{
    public int Id { get; set; }

    public string Pagina { get; set; }

    public virtual ICollection<Grafiche> Grafiche { get; set; } = new List<Grafiche>();

    public virtual ICollection<Notifica> Notifica { get; set; } = new List<Notifica>();
}