// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Redirezioni
{
    public int Id { get; set; }

    public string Url { get; set; }

    public bool Attiva { get; set; }
}