// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Template
{
    public string TemplateName { get; set; }

    public string TemplateBodyHtml { get; set; }

    public string TemplateHeaderHtml { get; set; }

    public string TemplateFooterHtml { get; set; }
}