// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Video
{
    public int Id { get; set; }

    public string Url { get; set; }

    public string Titolo { get; set; }

    public string Descrizione { get; set; }

    public string Provider { get; set; }

    public bool Attivo { get; set; }
}