// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Cinture
{
    public int Id { get; set; }

    public string Tipo { get; set; }

    public virtual ICollection<UtenteAtleta> UtenteAtleta { get; set; } = new List<UtenteAtleta>();
}