// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Organizzazioni
{
    public Guid RowGuid { get; set; }

    public string Nome { get; set; }

    public string Descrizione { get; set; }

    public string Indirizzo { get; set; }

    public string PartitaIva { get; set; }

    public virtual ICollection<UtenteAtleta> UtenteAtleta { get; set; } = new List<UtenteAtleta>();
}