// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Utente
{
    public string Nome { get; set; }

    public string Cognome { get; set; }

    public string CodFiscale { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool? IsAdmin { get; set; }

    public Guid RowGuid { get; set; }

    public bool IsMaestro { get; set; }

    public virtual ICollection<Abbonamento> Abbonamento { get; set; } = new List<Abbonamento>();

    public virtual ICollection<Documento> Documento { get; set; } = new List<Documento>();

    public virtual ICollection<IscrizioneEvento> IscrizioneEvento { get; set; } = new List<IscrizioneEvento>();

    public virtual UtenteAtleta UtenteAtleta { get; set; }

    public virtual UtenteInfo UtenteInfo { get; set; }
}