// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class UtentePrivacy
{
    public Guid RowGuid { get; set; }

    public bool? ConsensoInvioMail { get; set; }
}