// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class UtenteInfo
{
    public Guid RowGuid { get; set; }

    public DateTime? DataNascita { get; set; }

    public string Via { get; set; }

    public string Numero { get; set; }

    public string Citta { get; set; }

    public string Regione { get; set; }

    public string Nazione { get; set; }

    public virtual Utente Row { get; set; }
}