// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class UtenteAtleta
{
    public Guid Rowguid { get; set; }

    public Guid? Organizzazione { get; set; }

    public int? Cintura { get; set; }

    public virtual Cinture CinturaNavigation { get; set; }

    public virtual Organizzazioni OrganizzazioneNavigation { get; set; }

    public virtual Utente Row { get; set; }
}