// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Abbonamento
{
    public int Id { get; set; }

    public int TipoAbbonamento { get; set; }

    public Guid Utente { get; set; }

    public DateTime? DataIscrizione { get; set; }

    public DateTime? DataScadenza { get; set; }

    public string UrlPagamento { get; set; }

    public bool? Attivo { get; set; }

    public decimal? Importo { get; set; }

    public string IdCheckout { get; set; }

    public bool? Pagato { get; set; }

    public virtual TipoAbbonamento TipoAbbonamentoNavigation { get; set; }

    public virtual Utente UtenteNavigation { get; set; }
}