// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class TipoAbbonamento
{
    public int Id { get; set; }

    public string Descrizione { get; set; }

    public int? GiorniDurata { get; set; }

    public bool? ScadMensile { get; set; }

    public bool? ScadSettimanale { get; set; }

    public bool? ScadGiornaliera { get; set; }

    public virtual ICollection<Abbonamento> Abbonamento { get; set; } = new List<Abbonamento>();
}