// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Documento
{
    public Guid IdDocumento { get; set; }

    public Guid UtenteId { get; set; }

    public int TipoDocumentoId { get; set; }

    public string NomeDocumento { get; set; }

    public DateTime DataCaricamento { get; set; }

    public byte[] DatiDocumento { get; set; }

    public virtual TipoDocumento TipoDocumento { get; set; }

    public virtual Utente Utente { get; set; }
}