// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Categoria
{
    public int Id { get; set; }

    public string Descrizione { get; set; }

    public virtual ICollection<Gare> Gare { get; set; } = new List<Gare>();
}