// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Evento
{
    public Guid Id { get; set; }

    public string NomeEvento { get; set; }

    public DateTime DataInizioEvento { get; set; }

    public DateTime DataFineEvento { get; set; }

    public string LuogoEvento { get; set; }

    public string Categorie { get; set; }

    public string Descrizione { get; set; }

    public string Link { get; set; }

    public byte[] Copertina { get; set; }

    public decimal? ImportoIscrizione { get; set; }

    public DateTime? ChiusuraIscrizioni { get; set; }

    public virtual ICollection<Gare> Gare { get; set; } = new List<Gare>();

    public virtual ICollection<IscrizioneEvento> IscrizioneEvento { get; set; } = new List<IscrizioneEvento>();
}