// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class Gare
{
    public Guid Id { get; set; }

    public Guid Evento { get; set; }

    public string Nome { get; set; }

    public decimal? ImportoIscrizione { get; set; }

    public int? Categoria { get; set; }

    public virtual Categoria CategoriaNavigation { get; set; }

    public virtual Evento EventoNavigation { get; set; }

    public virtual ICollection<IscrizioneEvento> IscrizioneEvento { get; set; } = new List<IscrizioneEvento>();
}