// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SitoDeiSiti.DAL.Models;

public partial class IscrizioneEvento
{
    public Guid IdEvento { get; set; }

    public Guid IdUtente { get; set; }

    public string Note { get; set; }

    public Guid Gara { get; set; }

    public bool? Cancellata { get; set; }

    public virtual Gare GaraNavigation { get; set; }

    public virtual Evento IdEventoNavigation { get; set; }

    public virtual Utente IdUtenteNavigation { get; set; }
}